### ISSUE TITLE
[BUG] tool rack - tools don't hang vertically

### ISSUE THREAD

**Issue by matdoh** [MukiTanuki/armor-statues#20]
#### Issue Description:
when using the "tool rack"-auto align, the tools don't hang vertically anymore

#### What happens:
it. yes, look at the description.

Edit: Sticks are an exception. they hang beautifully. 

#### What you expected to happen:
the tool would hang vertically aligned like it used to do in older versions (1.16. is the last one I played before)

#### Steps to reproduce:

1. give an armor stand a tool
2. use tool rack

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.20.1
- Armor Statues: 2.8 to 2.10

- Single Player and/or Server? and
- Optifine? yes

#### Screenshots *(Optional)*
![Bild_2023-09-20_121128970](https://github.com/MukiTanuki/armor-statues/assets/72242257/569abd2f-ad4e-4ef8-86f0-308620c6fab3)

**Comment by MukiTanuki** [comment]
This is due to a resourcepack or mod you may have as tool rack armor stands appear to render correctly on my own client.  Try testing features like this without optifine or other resourcepacks or mods first before sending in bug reports please!
![2023-09-24_02 31 43](https://github.com/MukiTanuki/armor-statues/assets/52222394/e5b20d47-ed83-4e60-899d-be87a43014ff)
