### ISSUE TITLE
Vanilla Tweaks updates

### ISSUE THREAD

**Issue by alien-sunset** [MukiTanuki/armor-statues#5]
I asked over on VT and they said they needed you to contact them to allow them to update the Armor Statues version on their website.

As I know several people who only know about the book via them, it may be worth it so that people can get the most updated version.

**Comment by MukiTanuki** [comment]
I'm not part of the current VT team, so I don't particularly have a say in the matter and they have yet to communicate to me about updating the datapack on their site.  I do appreciate the interest in the datapacks though!  If anything VT should be pulling the files directly from curseforge instead of hosting them themselves.  However, since this isn't a bug I must close this as invalid.
